### ISSUE TITLE
Review and post OSPO Career Guide

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/work-day-activities#16]
https://docs.google.com/document/d/1iVLBuSl6MpBrspwdIYR9AAnJO_3jfG72uQhyCrAeWB4/edit

**Comment by gtback** [comment]
I got about halfway through reading this document. I'll try to do another pass later. I focused on a handful of trivial typesetting stuff, then took a look at overall clarity and order of topics presented. I didn't focus as much on writing style; there are a bunch of sentences I might reword for clarity, but I'm not the author so I didn't want to suggest those types of changes.

**Comment by gtback** [comment]
@caniszczyk I finished reviewing the document. Feel free to take or leave any of the suggestions. Overall I thought it was really well written and gets the point across well.

**Comment by 3cpt** [comment]
Shouldn't the document touch in the Inner Source area? At least mention that is something where a dedicated person can drive for it?

**Comment by anajsana** [comment]
I think this issue can be closed: https://todogroup.org/guides/career-development/
