### ISSUE TITLE
Review Open Source Commercial Ecosystem guide

### ISSUE THREAD

**Issue by anajsana** [todogroup/work-day-activities#20]
## Goal

Get the PR TODO Guide reviewed and merged

## Description

Issue about OS Commercial ecosystems' guide at: https://github.com/todogroup/todogroup.org/issues/227
See the PR at: https://github.com/todogroup/todogroup.org/pull/243

**Action Items**

- [ ] Review PR
- [ ] Merge PR

**Comment by gtback** [comment]
It looks like todogroup/todogroup.org#243 has been merged. I think todogroup/todogroup.org#227 can be closed, but I don't have permission to do that (todogroup/governance#106) or close this issue.

I'll take another look through the guide today.

**Comment by gtback** [comment]
I created todogroup/todogroup.org#258.

Once that's merged, I think this can be closed.
